const NEXT_PLAYER = 'NEXT_PLAYER';
const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';
const RESET_TO_PLAYER = 'RESET_TO_PLAYER';
const ADD_TURN = 'ADD_TURN';

export {
  NEXT_PLAYER,
  SET_CURRENT_PLAYER,
  RESET_TO_PLAYER,
  ADD_TURN,
};